### ISSUE TITLE
Feature Request - Align long lines automatically and syntax checking

### ISSUE THREAD

**Issue by vikas027** [irvinlim/vscode-language-modsecurity#1]
It would be a great idea to align long lines automatically. See below for example

```
SecRule REQUEST_HEADERS:Host "vikas027.something.com" \
  "id:'2727', phase:1, log, auditlog, pass, t:none, chain"
    "t:lowercase, t:normalisePath, t:removeWhitespace, t:urlDecodeUni, t:urlDecode, setvar:tx.inbound_anomaly_score_threshold=50, ctl:ruleRemoveById=200002"
```

can be
```
SecRule REQUEST_HEADERS:Host "vikas027.something.com" \
  "id:'2727', phase:1, log, auditlog, pass, t:none, chain"
      "t:lowercase, \
      t:normalisePath, \
      t:removeWhitespace, \
      t:urlDecodeUni, \
      t:urlDecode, \
      setvar:tx.inbound_anomaly_score_threshold=50, \
      ctl:ruleRemoveById=200002"
```

Also, some syntax checking would be awesome.

Thanks!

**Comment by irvinlim** [comment]
Hey @vikas027, great to see that you are using it!

Would love to help, unfortunately this plugin is only for syntax highlighting. What you're asking for is the job of a linter and a formatter, which requires parsing of the directives into an AST - which isn't an easy task!

If you are up for the challenge, we could discuss further! Unfortunately I don't think I would have the time to work on something that is so intense at the moment, especially since I don't work with ModSecurity as often anymore.

**Comment by vikas027** [comment]
Hey @irvinlim  ,

Thanks for the quick response. I understand it is not an easy task and might take some time to implement.

Sorry to hear that you are too busy to look at this request. I would love to be a part of it, but as you know time is the biggest challenge. However, I will let you know if I find time to work with you on the same.

Cheers!

**Comment by irvinlim** [comment]
If you wish to work on it, it would be a good idea to create a standalone binary such that it can work with any editor, or be part of CI! Like how [prettier](https://github.com/prettier/prettier), eslint or swiftlint works. Then we'll create a binding specifically for VS Code so that it can work within the editor itself.

If this is the case, then it would be out of the scope of this plugin already. I'll be closing this issue in this case.
